In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import warnings
warnings.filterwarnings('ignore')

import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
def extract_file_nc(param, wpp):
  ds = xr.open_dataset('/content/drive/MyDrive/overfishnt/data/fishing_spot_heatmap/'+param+'/'+wpp+'.nc')
  if param == 'chl':
    pass
  else:
    ds = ds.resample(time='D').mean()
  df = ds.to_dataframe().sort_values(by=['latitude','longitude'])
  df2=df.reset_index()
  for i in range(0, len(ds.longitude)):
    for j in range(0, len(ds.latitude)):
      lon = ds.longitude[i].values
      lat = ds.latitude[j].values
      new_df = df2.loc[(df2['longitude']==lon) & (df2['latitude']==lat)]
      count_nan = new_df[param].isna().sum()
      if count_nan == 0:
        break
  new_df = new_df.dropna().reset_index(drop=True)
  new_df = new_df[['time', param]]
  print(lon,lat,wpp)
  new_df.to_csv('/content/drive/MyDrive/overfishnt/data/fishing_spot_heatmap/'+param+'/csv_file/'+wpp+'.csv',index=False)

In [ ]:
WPP = ['WPP571', 'WPP572', 'WPP573', 'WPP711', 'WPP712', 'WPP713', 
       'WPP714', 'WPP715', 'WPP716', 'WPP717', 'WPP718']
param = ['chl','o2','sst']

In [ ]:
for i in WPP:
  for j in param : 
    extract_file_nc(j, i)

100.25 5.0 WPP571
100.25 5.0 WPP571
100.25 5.0 WPP571
100.0 -4.25 WPP572
100.0 -4.25 WPP572
100.0 -4.25 WPP572
112.5 -9.5 WPP573
112.5 -11.5 WPP573
112.5 -9.5 WPP573
108.5 -0.25 WPP711
108.5 -0.25 WPP711
108.5 -0.25 WPP711
113.0 -6.0 WPP712
112.0 -6.0 WPP712
112.0 -6.0 WPP712
119.0 -7.75 WPP713
119.0 -7.75 WPP713
119.0 -7.75 WPP713
127.5 -7.25 WPP714
127.5 -7.25 WPP714
127.5 -7.25 WPP714
127.0 -1.5 WPP715
127.0 -1.5 WPP715
127.0 -1.5 WPP715
125.0 1.75 WPP716
125.0 1.75 WPP716
125.0 1.75 WPP716
137.25 0.0 WPP717
137.25 0.0 WPP717
137.25 0.0 WPP717
136.5 -7.5 WPP718
136.5 -7.5 WPP718
136.5 -7.75 WPP718

In [ ]:
# 112.5 -11.5 WPP573, harusnna lat = -9.5 -> o2
# 136.5 -7.75 WPP718, harusnya lat = -7.5 -> sst

ds = xr.open_dataset('/content/drive/MyDrive/overfishnt/data/fishing_spot_heatmap/'+'o2'+'/'+'WPP573'+'.nc')
ds = ds.resample(time='D').mean()
df = ds.to_dataframe()
df2= df.reset_index()
new_df = df2.loc[(df2['longitude']==112.5) & (df2['latitude']==-9.5)]
count_nan = new_df['o2'].isna().sum()
print(count_nan)
new_df = new_df.reset_index(drop=True)
new_df = new_df[['time', 'o2']]
new_df.to_csv('/content/drive/MyDrive/overfishnt/data/fishing_spot_heatmap/'+'o2'+'/csv_file/'+'WPP573'+'.csv',index=False)
new_df

0

          time          o2
0   2021-01-01  200.445160
1   2021-01-02  200.020630
2   2021-01-03  200.451401
3   2021-01-04  200.710388
4   2021-01-05  200.641678
..         ...         ...
871 2023-05-22  203.659363
872 2023-05-23  203.480972
873 2023-05-24  203.466309
874 2023-05-25  203.512512
875 2023-05-26  203.511002

[876 rows x 2 columns]

In [ ]:
# 112.5 -11.5 WPP573, harusnna lat = -9.5 -> o2
# 136.5 -7.75 WPP718, harusnya lat = -7.5 -> sst

ds = xr.open_dataset('/content/drive/MyDrive/overfishnt/data/fishing_spot_heatmap/'+'sst'+'/'+'WPP718'+'.nc')
ds = ds.resample(time='D').mean()
print(ds)
df = ds.to_dataframe()
df2= df.reset_index()
new_df = df2.loc[(df2['longitude']==136.5) & (df2['latitude']==-7.5)]
count_nan = new_df['sst'].isna().sum()
print(count_nan)
new_df = new_df.dropna().reset_index(drop=True)
print(count_nan)
new_df = new_df[['time', 'sst']]
new_df.to_csv('/content/drive/MyDrive/overfishnt/data/fishing_spot_heatmap/'+'sst'+'/csv_file/'+'WPP718'+'.csv',index=False)
new_df

<xarray.Dataset>
Dimensions:    (longitude: 16, latitude: 12, expver: 2, time: 869)
Coordinates:
  * longitude  (longitude) float32 132.8 133.0 133.2 133.5 ... 136.0 136.2 136.5
  * latitude   (latitude) float32 -5.0 -5.25 -5.5 -5.75 ... -7.25 -7.5 -7.75
  * expver     (expver) int32 1 5
  * time       (time) datetime64[ns] 2021-01-01 2021-01-02 ... 2023-05-19
Data variables:
    sst        (time, expver, latitude, longitude) float32 302.7 302.7 ... 301.8
Attributes:
    Conventions:  CF-1.6
    history:      2023-05-24 11:21:07 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...
869
869

          time         sst
0   2021-01-01  302.492340
1   2021-01-02  302.456055
2   2021-01-03  302.441620
3   2021-01-04  302.180389
4   2021-01-05  302.102570
..         ...         ...
864 2023-05-15  302.016083
865 2023-05-16  302.207458
866 2023-05-17  302.144989
867 2023-05-18  302.042480
868 2023-05-19  301.906952

[869 rows x 2 columns]